apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2VDxk7lGkxPAunAKxLbV5q8eRNg=,iv:olt+Y8OKQsyhbi2yuAFAfi8TsiUndtzbnqofJ/wXfH0=,tag:ENLeVCVAj9y2LPmmx4u8vA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:jm2U38jeGFUSmlcuWJ/cv302vjFHTsWC4WB1psnVUlLR4hYpMw==,iv:XZqT2Ia5mqCQre8YuGwp0Oxf/NqZ5X0cgc2euvVQpHk=,tag:pCGm/UNR/LiKGMiX5cyB+g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:StXFMfAF2H4D/+UPZnCtSdE=,iv:+ZZeshX48huviA8ywatpkO/HENT15XlFkj4j0pYa8Sk=,tag:xdSFiWa6zG11e56rvIUnYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1799exegft0rpv6vdv5c6ts9l66wcnf83rm0vpktedxxjy69up4dqzt30ss
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSazFXZ3YrcVZJV1VzOU9H
            LzRQRkZzR3Q0RDBjSUJES1F1cG90VGJmb1NNCjZWa1JlOXNxbmlQZnQwZ1pyWTli
            bmRQNk1RVnZTaWhxd0o2RXVHUzFnNkkKLS0tIEloZS9mRVRHSGphRUo5MUo0di8z
            a1JGUExKT3JtckprMmIzMlBwNXVFbFkKj6i815aHOHKHyTJJy+oU/uOolYDAWU+y
            TYeZuw5wyLHyo0rTYgDgrhel3U7CkRgwhogvp1O5LCeQkE/NBhcT1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:01:57Z"
    mac: ENC[AES256_GCM,data:8+2/xmgaWo8/LoHdhOyPhTtZnLJvPgmvnDPiy/EG5ZAprknCgolWQgrxeo9wpWflCZ2aga23xEcxcbjLCCoVgpvgu3SnOAGrDKJ64X8SsNxmn+1jUUahDQioszbhrvUZQVwtcSXpnhUTxWClK5o/c3dqAFn/ZJqf8mp4pbr5SgE=,iv:rNQFUBOmEzyWNkgNmsyN71Z2bqmAv7e6ioJmvvH19kE=,tag:md76jZA4R9LkniTFInDB5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
