kind: ENC[AES256_GCM,data:hYKznooF,iv:69N32QB1Q1L7EijIwAHShj2aebI5JtSOgXGoIvF7F5A=,tag:OAEQODHKkHuPa+7N2VSYtQ==,type:str]
ansible_user: ENC[AES256_GCM,data:+QOM7g==,iv:QbDnfzkJtZUGtS8UqzXS3PcRCPgfgE2zyY9/fJWLBh4=,tag:QbC1GOnbjShbf3fTeQzQ8Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:LchpNjM2,iv:ann+XugaQiQ5mUsPvbrVJgrk13co9lxvsI/SAwzrE4c=,tag:oM3dLLX82Jhx0GCpU7Iz5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1799exegft0rpv6vdv5c6ts9l66wcnf83rm0vpktedxxjy69up4dqzt30ss
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLczZKbitMTk9qbG90ZkJw
            WElpZWZpUjEvQzdaeTBDc2VodjBBWWtyTHdNCkVSQU5ZMjVveXJmQkptRWxMOWJs
            L09MQlNQSU9IcjF2WG9KUlQwc1AybTgKLS0tIGtWUUxNVW12TWI1QnNtSXlzT3lE
            TXZIVnBlT0cybmFlVmtIaTA0bkp6aE0K7Fuo3krXLzKrtx/Df1CPXYyZDjAYFt3a
            fyhGzZwqQGhM1Gfg6WSGEoRd2WMvhywWKrNdeyf2iVzUTK55kOurJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T04:54:42Z"
    mac: ENC[AES256_GCM,data:r+oqhbo+RH0xHkwjwfEo6ug4MFMPp8r2ZgvzLsHKy7u3TjK8cuFhldPiUcEvEU2J0mCpR81YauiLiB/0YnkahhAuTxgU2CgAVFT4oaH4S0pK1u2BzpB9ZeY1vM9DV+i5CwY5l1zvb29cdNvoPjHNAfJvqpXTzEEVJegHWXnov24=,iv:ZCJ8H15F5I/TM96RxJN4JyocD+tTUkH9MP2/BcHPasU=,tag:1hsGqR4vVbY5ghCKZYQVuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
