apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RWE+liw1aGDXyI+vIiqnvD57HIwmtl8M7K0lsZ4y454vR7P9rhS66A==,iv:C8j9Pk3GG8ZyR4xDtp4d7NmVzqDE/L4iHz4cV+MnEpE=,tag:Pb5QVSLPbmChfK9ZDrtuEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1799exegft0rpv6vdv5c6ts9l66wcnf83rm0vpktedxxjy69up4dqzt30ss
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZWJyMnVRaWJha1pUWUtG
            enRocDNweDdUZTYxSXI3ZlNzMEFZZjF0UW5NCmlYVjBMT0R1R3ZBSDl1NFc2TW5M
            VVp3WStqM2xKS1NIRjdhaExRcW9yVncKLS0tIHBzaC96UVYrZnNJYmEwalE4QmZ2
            VUdSb0tkdENSWW4xV05BTEFIZlVCb3MKlTi9Me04HMW6p4JDItzLuyfa4jUS1XQ1
            wEAHRl3oc3XbYmzt3YucMyqJmhSKp7HK5syia1y/9DxVw8+0blfwiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:01:57Z"
    mac: ENC[AES256_GCM,data:OVwSx7afAg/kdt4AmZIvrseAw4JCOLIjsbMKi1QDv1PQgJFY56cRGwqPHm8/x7TlmT+s+gpM/5FiCepT77VXv4S4OuFCWfbeyljVtpUHGX4yqpTF0Ghd2GvOdibLQ2VLCwp9gIoAT2fVWIpZKUU+R1zvD1gVP95ehiPIMuvBDgI=,iv:KbscHrhE939SzbNRLOAGrJ2lczQB82m8+/3CzI8bS30=,tag:M4OmZSR5UzKBKRqL9DxGaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
