---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.7.2
          rook_devices: /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_5QJSXPEB
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.7.3
          # rook_devices: /dev/disk/by-id/nvme-KINGSTON_OM8SEP4512N-A0_50026B7381C1F709-part4
        k8s-2:
          ansible_host: 192.168.7.4
          # rook_devices: /dev/disk/by-id/nvme-KINGSTON_OM8SEP4512N-A0_50026B7381C1EEFE
        k8s-3:
          ansible_host: 192.168.7.5
          # rook_devices: /dev/disk/by-id/nvme-KINGSTON_OM8SEP4512N-A0_50026B7381C1EE9E
