---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.7.2
          rook_devices: /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_5QJSXPEB
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.7.3
        k8s-2:
          ansible_host: 192.168.7.4
        k8s-3:
          ansible_host: 192.168.7.5
