---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-unifi
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
  interval: 10m
  path: ./kubernetes/apps/networking/unifi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
