---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-unifi
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-cluster
  interval: 10m
  path: ./kubernetes/apps/networking/unifi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
