apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:OZdYKFAmwteSd1plkmXAQYbIzNrMuUVbKL+RARi1p5Y+GqpSOxGdKznCsBUZkBT1nyrPyq0Y3wkWjukw,iv:fbh/yTANKem00O40X0/z4q6+ld0/7bNTlSulWYMgOXE=,tag:fMob0USasJdqWVfhO9sS7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1799exegft0rpv6vdv5c6ts9l66wcnf83rm0vpktedxxjy69up4dqzt30ss
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc2REQW9FNWhtY2ZUL2ta
            OGFFanU1QjRPaEM4U2FidmZrUXloYVJ5R1JBCkRVcXRNNnc1NXVOSnZGOTVzQ0N3
            MjFaekhPaE02MGhhai93SHFPSVBxUVkKLS0tIFVHVTFrR3VaVVdIc09HNW5va1Jj
            UlpRcjd1Q21hT2ZUKzhYaTBJcU9xbHcKFtUM0G/jfanwH7wYY4sOqz3hwoSx07xm
            YZN98XocvGu9xb7aDjKDjXVotJydJm9DGV19XJdWzW9SLObcy4qv6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:01:58Z"
    mac: ENC[AES256_GCM,data:kfG0NNdtPJdcJ28YzxEbX0Kuhv34L2OeEGcjU5rmRdblt7QFMgTY2MsujUmi63bbemm6cRaqV/z/YUydxdp7qr0HICUBMvmQ+ZHFS71uHGet7tmoZkO1eO4vmygCWhO3HFkpEUGWrwEh4XV426X8KKhq1IdtZtTJ6wJkt6sy+20=,iv:G4n7koTDH5rPcA/BG2kttKnScuHSqXDnHDSeZolILvM=,tag:amxxwUK5SGYY5kE0Z9faDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
