apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:wubztfoiSZsrW2XGaQXmRi2vFmrzXGsMZ7RjLNT2TLu0pxz8RhB6M67hptiY0hCgnQhSuSXE/eAj4L8q,iv:QwWrNQyonctfxU4Rpp97aBxzK8hJNZR81vkx1FjsB+8=,tag:59NpdPEZudxctKrEt4EGeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1799exegft0rpv6vdv5c6ts9l66wcnf83rm0vpktedxxjy69up4dqzt30ss
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRDhaOU0xQ004L1c3SUVi
            akF4RkJnV1BaMndhWFVTeDRyZlNURzU1S3dBCndMSlBBaTA5M0dTN0xabjZVRmRV
            bldQcDQyZGhvYVlkc3VJNjU0RlNSSHMKLS0tIERRdVMvR1NKTGlHdWhJMlM0Zjg3
            N3pMTXJqREZXaCs4eHpOSXg3Z1ViTWsKweZPxPbBeL1SlBctrKbJEXmVH7TrGbE8
            66xlJ0gZyyB3EPqT6UZUYX0WOA/rVw38O7K4kOd6Hcj0dGTsQyznGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-23T00:15:52Z"
    mac: ENC[AES256_GCM,data:Ikaa3GVV9pcLy2RZ/XtaGgjS7E1vt1mxKI4uQL6CLhnVVnoNAXqjlMlXuWig2jrPO64csrM5HopWDhxU5Og0AI4A8W2jV3uZkwpHFR0/UAN/DSka/FrEU4V/SbzIYVOfYqtO2IAx3+Ot3EgfmRWsVrkOccMjPTn12dJ/1V57loU=,iv:E5pIefVFMka1NE05kZlMNqOnwbwn4F73S9uFiwTiMy8=,tag:LIskwNhYVeRnkOtW0aDqqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
