---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "192.168.7.254"
  METALLB_LB_RANGE: "192.168.7.220-192.168.7.230"
  METALLB_K8S_GATEWAY_ADDR: "192.168.7.220"
  METALLB_INGRESS_ADDR: "192.168.7.221"
  METALLB_UNIFI_ADDR: "192.168.7.222"
