apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iHEAVBI+9ki2MTbx,iv:wwVSgvXpBawWcngWL6ImKjC8K81AN9f8ZEJtwqvxed8=,tag:k6nK3zpyJPkwo0Ve0YufLA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:F4kbgvAcu2Yd63KkH2nWUYxqle0=,iv:BbwxWQIu+MmG00To4Iwld5+G4Lzyx0AP+Rhqu0gdEtA=,tag:o7mb+LPlRDxaDz8Wg0Xggg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1799exegft0rpv6vdv5c6ts9l66wcnf83rm0vpktedxxjy69up4dqzt30ss
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORmVyVU5yampSYklZdXFz
            N01hSmNMMjBld3FwTGtTVCtxQ2plVUgzcVI4Ck45cTVyVXpWb3FFKzJtMGUwL21M
            K3pIektDcUxlVnd5Nk9WWWJ6ak1TVDQKLS0tIGM5QWlnMUVIWnYwWjBkNzlUSlBp
            cFZDVXJtTVF0NG8wYkhoc05xK1NSMDgKShRuZtDJXkypjIkWvjfvuggsgcHDut/2
            +4bhPJivGCuQbJiLInGhYEjQ/8uLEgxwUYq46i3f9Sd88J6LP6eXuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:01:57Z"
    mac: ENC[AES256_GCM,data:pG7c250dAZ2lR1NKVlZRvLjhx3Sk6v59+5n28tAQpYA2zYyeasluc6rlTBbqjfTpEIXSdIaVddL8LTW6cCME0iErvuZOI84feVpFvyuldcNEwoOPdy5SkJJmHM3hd3kzbAqh5tdkyXgqvjJpw6JJJn4oRcuE81HLUVS9lN7FP4c=,iv:nRkLGQRekS4/kfrOvVZtWWnQci9MKmbRxRFOxzZAsEM=,tag:YPHT1gUyawpi2bqvzXOjuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
