---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data
  namespace: networking
  labels:
    app.kubernetes.io/name: &name unifi
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
